const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');

const replacements = [
  {
    file: 'bulk_import.php',
    fixes: [
      ['✅ ZIP extracted — <?= count($extracted) ?> added to the import queue.', '<span data-i18n-text="bulk_import.zip_extracted">✅ ZIP extracted — </span><?= count($extracted) ?> <span data-i18n-text="bulk_import.added_to_import_queue">added to the import queue.</span>'],
      ['Skipped: <?= count($skipped) ?>.', '<span data-i18n-text="bulk_import.skipped">Skipped: </span><?= count($skipped) ?>.']
    ]
  },
  {
    file: 'bulk_import_csv.php',
    fixes: [
      ['<th><?= htmlspecialchars($col) ?></th>', '<th><span data-i18n-text="bulk_import_csv.col_<?= htmlspecialchars(strtolower($col)) ?>"><?= htmlspecialchars($col) ?></span></th>'],
      ['<span class="font-medium"><?= $mapped_count ?></span> skipped', '<span class="font-medium"><?= $mapped_count ?></span> <span data-i18n-text="bulk_import_csv.skipped">skipped</span>'],
      ['<span class="font-medium"><?= $mapped_count ?></span> failed', '<span class="font-medium"><?= $mapped_count ?></span> <span data-i18n-text="bulk_import_csv.failed">failed</span>'],
      ['<span class="font-medium"><?= $mapped_count ?></span> queued for enrichment', '<span class="font-medium"><?= $mapped_count ?></span> <span data-i18n-text="bulk_import_csv.queued_for_enrichment">queued for enrichment</span>'],
      ['<h3>Preview (first <?= count($preview_rows) ?> rows of data)</h3>', '<h3><span data-i18n-text="bulk_import_csv.preview_first">Preview (first </span><?= count($preview_rows) ?> <span data-i18n-text="bulk_import_csv.rows_of_data">rows of data)</span></h3>'],
      ['🔗 Running enrichment for <?= count($results[\'enriched\']) ?> items…', '<span data-i18n-text="bulk_import_csv.running_enrichment_for">🔗 Running enrichment for </span><?= count($results[\'enriched\']) ?> <span data-i18n-text="bulk_import_csv.items">items…</span>']
    ]
  },
  {
    file: 'bulk_import_folder.php',
    fixes: [
      ['Ready — <span id="queue-count" class="font-medium text-white"><?= count($items) ?></span> items queued', '<span data-i18n-text="bulk_import_folder.ready">Ready — </span><span id="queue-count" class="font-medium text-white"><?= count($items) ?></span> <span data-i18n-text="bulk_import_folder.items_queued">items queued</span>'],
      ['📁 <?= count($info[\'images\']) ?> image<?= count($info[\'images\'])!==1?\'s\':\'\' ?> · pending', '📁 <?= count($info[\'images\']) ?> <span data-i18n-text="bulk_import_folder.images">image(s)</span> · <span data-i18n-text="bulk_import_folder.pending">pending</span>']
    ]
  },
  {
    file: 'container_manifest.php',
    fixes: [
      ['<?= $stats[\'types\'] ?> component types &middot; <?= $stats[\'units\'] ?> total units', '<?= $stats[\'types\'] ?> <span data-i18n-text="container_manifest.component_types">component types</span> &middot; <?= $stats[\'units\'] ?> <span data-i18n-text="container_manifest.total_units_count">total units</span>'],
      ['📄 Container QR Sticker — <?= htmlspecialchars($loc_name) ?>', '<span data-i18n-text="container_manifest.container_qr_sticker">📄 Container QR Sticker — </span><?= htmlspecialchars($loc_name) ?>'],
      ['Items with location "<?= htmlspecialchars($loc_name) ?>" will appear here.', '<span data-i18n-text="container_manifest.items_with_location">Items with location </span>"<?= htmlspecialchars($loc_name) ?>" <span data-i18n-text="container_manifest.will_appear_here">will appear here.</span>'],
      ['☐ = verify item is in container &nbsp;|&nbsp; Generated by DIY Lab Inventory System', '<span data-i18n-text="container_manifest.verify_item_is_in_container">☐ = verify item is in container &nbsp;|&nbsp; Generated by DIY Lab Inventory System</span>'],
      ['🏷️ Print Item Labels', '<span data-i18n-text="container_manifest.print_item_labels">🏷️ Print Item Labels</span>']
    ]
  },
  {
    file: 'dashboard.php',
    fixes: [
      ['<?= $pagination[\'total_items\'] ?> unique parts', '<?= $pagination[\'total_items\'] ?> <span data-i18n-text="dashboard.unique_parts_count">unique parts</span>'],
      ['<?= $pagination[\'total_qty\'] ?> across all items', '<?= $pagination[\'total_qty\'] ?> <span data-i18n-text="dashboard.across_all_items">across all items</span>'],
      ['<?= count($categories) ?> component groups', '<?= count($categories) ?> <span data-i18n-text="dashboard.component_groups_count">component groups</span>'],
      ['Showing <?= count($items) ?> of <?= $pagination[\'total_items\'] ?> components', '<span data-i18n-text="dashboard.showing">Showing </span><?= count($items) ?> <span data-i18n-text="dashboard.of">of</span> <?= $pagination[\'total_items\'] ?> <span data-i18n-text="dashboard.components">components</span>']
    ]
  },
  {
    file: 'item_details.php',
    fixes: [
      ['Quantity: <?= $item[\'quantity\'] ?>', '<span data-i18n-text="item_details.quantity_label">Quantity: </span><?= $item[\'quantity\'] ?>'],
      ['Location: <?= htmlspecialchars($item[\'location\']) ?>', '<span data-i18n-text="item_details.location_label">Location: </span><?= htmlspecialchars($item[\'location\']) ?>'],
      ['Condition: <?= $item[\'status\'] ?>', '<span data-i18n-text="item_details.condition_label">Condition: </span><?= $item[\'status\'] ?>'],
      ['Added: <?= substr($item[\'created_at\'], 0, 10) ?>', '<span data-i18n-text="item_details.added_label">Added: </span><?= substr($item[\'created_at\'], 0, 10) ?>']
    ]
  }
];

let replacedKeys = {};

replacements.forEach(task => {
  let content = fs.readFileSync(path.join(ROOT_DIR, task.file), 'utf8');
  let updated = false;
  
  task.fixes.forEach(fix => {
    if (content.includes(fix[0])) {
      content = content.replace(fix[0], fix[1]);
      updated = true;
      const keyMatches = [...fix[1].matchAll(/data-i18n-text="([^"]+)">([^<]+)<\/span>/g)];
      keyMatches.forEach(match => {
         replacedKeys[match[1]] = match[2];
      });
    } else {
      console.log(`Could not find in ${task.file}: ${fix[0]}`);
    }
  });

  if (updated) {
    fs.writeFileSync(path.join(ROOT_DIR, task.file), content, 'utf8');
    console.log(`Updated ${task.file}`);
  }
});

fs.writeFileSync(path.join(ROOT_DIR, 'tests', 'dynamic_keys.json'), JSON.stringify(replacedKeys, null, 2));
console.log('Dynamic keys exported to tests/dynamic_keys.json');
