<?php
/**
 * DIY Lab Inventory System - Installation Validation Test
 * CLI test runner to verify installation business logic, diagnostics, and config generation.
 */

if (php_sapi_name() !== 'cli') {
    die("This script can only be run via the CLI (command line interface).\n");
}

echo "==================================================\n";
echo "    DIY Lab Installer Automated Validation Test   \n";
echo "==================================================\n\n";

$pass_count = 0;
$fail_count = 0;

function assertTest($description, $assertion) {
    global $pass_count, $fail_count;
    if ($assertion) {
        echo "  [PASS] $description\n";
        $pass_count++;
    } else {
        echo "  [FAIL] $description\n";
        $fail_count++;
    }
}

// -----------------------------------------------------------------
// Test 1: Simulating Environment Checking Logic
// -----------------------------------------------------------------
echo "Running Test Suite 1: Environment Checker...\n";

$mock_php_version_pass = version_compare('8.2.0', '8.0.0', '>=');
$mock_php_version_fail = version_compare('7.4.29', '8.0.0', '>=');

assertTest("PHP Version 8.2.0 meets 8.0.0 requirement", $mock_php_version_pass === true);
assertTest("PHP Version 7.4.29 fails 8.0.0 requirement", $mock_php_version_fail === false);

$test_extensions = ['pdo', 'pdo_mysql', 'mbstring', 'curl', 'gd'];
$all_exts_loaded = true;
foreach ($test_extensions as $ext) {
    if (!extension_loaded($ext)) {
        $all_exts_loaded = false;
    }
}
echo "  [INFO] Required extensions check: " . ($all_exts_loaded ? "All loaded on current host" : "Some missing on current host") . "\n";
assertTest("Critical PDO extensions are checkable", extension_loaded('pdo') !== null);

echo "\n";

// -----------------------------------------------------------------
// Test 2: Testing Configuration File Template Generation
// -----------------------------------------------------------------
echo "Running Test Suite 2: Config Generator...\n";

$db_host = '127.0.0.1';
$db_name = 'test_diy_db';
$db_user = 'test_user';
$db_pass = 'secret\'pass"word';
$site_url = 'http://localhost/diy';

$config_template = <<<EOT
<?php
/**
 * DIY Lab Inventory System - Production Configuration
 * Generated by the Setup Wizard.
 */

define('DB_HOST', %s);
define('DB_NAME', %s);
define('DB_USER', %s);
define('DB_PASS', %s);
define('SITE_URL', %s);
EOT;

$generated_config = sprintf(
    $config_template,
    var_export($db_host, true),
    var_export($db_name, true),
    var_export($db_user, true),
    var_export($db_pass, true),
    var_export($site_url, true)
);

assertTest("Config contains DB_HOST constant", strpos($generated_config, "define('DB_HOST', '127.0.0.1')") !== false);
assertTest("Config contains DB_NAME constant", strpos($generated_config, "define('DB_NAME', 'test_diy_db')") !== false);
assertTest("Config contains DB_USER constant", strpos($generated_config, "define('DB_USER', 'test_user')") !== false);
assertTest("Config handles quote escaping in password", strpos($generated_config, "define('DB_PASS', 'secret\'pass\"word')") !== false);
assertTest("Config contains SITE_URL constant", strpos($generated_config, "define('SITE_URL', 'http://localhost/diy')") !== false);

echo "\n";

// -----------------------------------------------------------------
// Test 3: Testing Diagnostic Logger & Masking Logic
// -----------------------------------------------------------------
echo "Running Test Suite 3: Diagnostic Logger & Sensitive Masking...\n";

// We re-implement the masking logic locally to verify it behaves exactly as the installer
function test_mask_data($step, $error_msg, $extra_data) {
    $masked_data = $extra_data;
    if (isset($masked_data['db_pass'])) {
        $masked_data['db_pass'] = '********';
    }
    if (isset($masked_data['admin_password'])) {
        $masked_data['admin_password'] = '********';
    }
    if (isset($masked_data['admin_confirm_password'])) {
        $masked_data['admin_confirm_password'] = '********';
    }
    return $masked_data;
}

$sensitive_post = [
    'db_host' => 'localhost',
    'db_name' => 'diy_db',
    'db_user' => 'admin',
    'db_pass' => 'super_secret_db_password_123',
    'admin_password' => 'secret_admin_pass',
    'admin_confirm_password' => 'secret_admin_pass'
];

$masked_result = test_mask_data('test_step', 'database error', $sensitive_post);

assertTest("Sensitive database password is masked", $masked_result['db_pass'] === '********');
assertTest("Sensitive admin password is masked", $masked_result['admin_password'] === '********');
assertTest("Sensitive admin confirm password is masked", $masked_result['admin_confirm_password'] === '********');
assertTest("Non-sensitive host is preserved", $masked_result['db_host'] === 'localhost');
assertTest("Non-sensitive user is preserved", $masked_result['db_user'] === 'admin');

echo "\n";

// -----------------------------------------------------------------
// Test 4: Database Credentials Connection Flow Simulation
// -----------------------------------------------------------------
echo "Running Test Suite 4: Database Connection Mocking...\n";

// Simulate database connection testing on invalid credentials
function simulate_db_connection_test($host, $name, $user, $pass) {
    try {
        // Using short timeout to fail fast
        $dsn = "mysql:host=$host;dbname=$name;charset=utf8mb4";
        $conn = @new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_TIMEOUT => 2
        ]);
        return ['success' => true];
    } catch (PDOException $e) {
        return ['success' => false, 'error' => $e->getMessage()];
    }
}

// We expect this to fail because of invalid host IP
$result_fail = simulate_db_connection_test('192.0.2.1', 'dummy', 'dummy', 'dummy');
assertTest("Connection test with invalid host fails gracefully", $result_fail['success'] === false);
assertTest("Failed connection yields database exception message", !empty($result_fail['error']));

echo "\n";

// -----------------------------------------------------------------
// Test Summary
// -----------------------------------------------------------------
echo "==================================================\n";
echo "    TEST SUMMARY                                  \n";
echo "==================================================\n";
echo "  Total Tests Run: " . ($pass_count + $fail_count) . "\n";
echo "  Passed: $pass_count\n";
echo "  Failed: $fail_count\n";
echo "==================================================\n";

if ($fail_count > 0) {
    exit(1);
} else {
    exit(0);
}
